### ISSUE TITLE
Review Code for Use of "Incorrect" Language

### ISSUE THREAD

**Issue by andrewk10** [andrewk10/AutoCompliance#16]
**Is your feature request related to a problem? Please describe.**
Net_propagation.py and Main.py started off as scripts for maliciously sharing and executing scripts across a controlled network as part of a student project, thus some naming conventions are a little outdated.

**Describe the solution you'd like**
Revised, reviewed and edited where needed naming conventions and language in the code to give a better idea of what the code is actually trying to do.

**Describe alternatives you've considered**
Ignoring it altogether, though I don't think it bodes well if something like "try_attack" is used in a cyber-security defence tool such as this. :)

**Additional context**
Based on the TODO here;
![image](https://user-images.githubusercontent.com/19553807/151850275-09562905-3e16-41b9-a4f1-ccb04b2ba835.png)

Example of the kind of language that needs to be changed;
![image](https://user-images.githubusercontent.com/19553807/151850491-505fd202-7152-47dc-b187-22ec0365e145.png)

**Comment by NeelPatel31** [comment]
Which type of "Incorrect" language do you want to review ?
Can you explain the issue briefly ?

**Comment by andrewk10** [comment]
> Which type of "Incorrect" language do you want to review ?
> Can you explain the issue briefly ?

Incorrect in this case being inaccurate to the actual purpose of the application. We're not “attacking” other hosts we're “propagating" to them. I'll be uploading some workflows, use cases and technical architecture documents soon that will paint a better picture of the “correct” language to be used.

In the meantime, see the assignment which inspired the propagation tactics for this project to get an idea of what's “incorrect”; https://mega.nz/file/3kg21ZqZ#jztu8Kcs5l0Zx7Lx15wKyNh_Gih8E7EZ-12Viza17sc

**Comment by andrewk10** [comment]
Done as part of #20
