### ISSUE TITLE
Add all strings to strings.py

### ISSUE THREAD

**Issue by andrewk10** [andrewk10/AutoCompliance#17]
**Is your feature request related to a problem? Please describe.**
Currently, there's a lot of hard coded strings that duplicate across multiple functions, and even the ones that don't are likely to be duplicated in the future. Changing a string in one place doesn't change it across the application.

**Describe the solution you'd like**
Put all strings into the "strings.py"

**Describe alternatives you've considered**
None

**Additional context**
Example of a string which needs to be pulled out into strings.py;
![image](https://user-images.githubusercontent.com/19553807/151851617-d39f5bef-0091-499d-b696-622b6add6c25.png)

**Comment by andradenathan** [comment]
So, what you need is a function that returns according to this conditional in strings.py, right?

**Comment by andrewk10** [comment]
> So, what you need is a function that returns according to this conditional in strings.py, right?

Yes, but the function should only do that of course. Any logic unrelated to string building should stay where it is for now.

**Comment by andrewk10** [comment]
Done as part of #20
