### ISSUE TITLE
[Proposal] Refactoring the codebase

### ISSUE THREAD

**Issue by 0x30c4** [andrewk10/AutoCompliance#38]
[net_propagation.py](https://github.com/andrewk10/AutoCompliance/blob/main/src/net_propagation.py) is full with functions but instead of that if we can make a class named NetPropagation which will handle all the functionality of current net_propagation then it would be much better and after that we can work on the argument parsing of the main program. We can use a lib like (argparse)[https://docs.python.org/3/library/argparse.html] so that the program will be more user friendly overall and the code will be more manageable.
Let me know what do you think about it.

**Comment by andrewk10** [comment]
Totally agree, it's important to note too that net_propagation is really monolithic in nature. A lot of the functions are better suited for a different class or probably have functionality that would be better handled by a pre-exising lib such as convert_file_to_list(), I'll link other refactor issues to this one and it can be looked at as a whole in a separate pull request.

**Comment by 0x30c4** [comment]
I got it.

**Comment by andrewk10** [comment]
Done :)
