### ISSUE TITLE
[UPDATE] main.py as a demo script

### ISSUE THREAD

**Issue by andrewk10** [andrewk10/AutoCompliance#40]
**Is your feature request related to a problem? Please describe.**
Main.py is a carryover from older purposes, it really serves no purpose anymore, especially in light of upcoming refactors.

**Describe the solution you'd like**
Repurpose main.py as a demo/testing script for back-end functionality

**Describe alternatives you've considered**
Removing it altogether, but a demo script is needed anyway so ¯\_(ツ)_/¯

**Additional context**
None

**Comment by 0x30c4** [comment]
I think I can start to implement those features from this weekend.

**Comment by andrewk10** [comment]
> I think I can start to implement those features from this weekend.

No pressure, I'm currently writing the research report for university so I'll be taking time out from the code for a week or two. Feel free to commit changes to #39 :)

**Comment by andrewk10** [comment]
Btw, might rob your readme.md on your profile, it's bougie.

**Comment by 0x30c4** [comment]
@andrewk10 sure, thanks!

**Comment by andrewk10** [comment]
This issue is closed now :)
